version: "3"

vars:
  IMAGE: ghcr.io/xusenlin/workavera
  VERSION:
    sh: cat VERSION

tasks:
  default:
    desc: 显示可用任务
    cmds:
      - task --list
    silent: true

  dev:ui:
    desc: 启动前端开发服务器
    dir: frontend
    cmds:
      - pnpm dev

  dev:go:
    desc: 启动 Go 后端开发服务器
    cmds:
      - go run -ldflags="-X main.version={{.VERSION}}" . serve

  build:ui:
    desc: 在宿主机上构建前端资源
    dir: frontend
    cmds:
      - pnpm build

  build:go:
    desc: 构建 Go 二进制
    cmds:
      - go build -trimpath -ldflags="-s -w -X main.version={{.VERSION}}" -o workavera .

  run:
    desc: 编译并运行 Go 二进制
    deps:
      - build:go
    cmds:
      - ./workavera serve

  build:docker:
    desc: 打包前端并构建本地 Docker 镜像
    deps:
      - build:ui
    cmds:
      - docker build --build-arg VERSION={{.VERSION}}  -t {{.IMAGE}}:latest .

  push:
    desc: 构建 CentOS 服务器使用的 linux/amd64 镜像并推送
    deps:
      - build:ui
    cmds:
      - >-
        docker buildx build
        --platform linux/amd64
        --build-arg VERSION={{.VERSION}}
        --tag {{.IMAGE}}:{{.VERSION}}
        --tag {{.IMAGE}}:latest
        --push
        .

  test:
    desc: 运行测试
    cmds:
      - go test ./...

  tidy:
    desc: 整理 Go 模块依赖
    cmds:
      - go mod tidy
