import { useRef, useState } from "react"

import { createAvatar } from "@dicebear/core"
import {
  adventurer,
  avataaars,
  bigSmile,
  bottts,
  funEmoji,
  lorelei,
  micah,
  notionists,
  shapes,
  thumbs,
} from "@dicebear/collection"

import { HugeiconsIcon } from "@hugeicons/react"
import { Upload04Icon } from "@hugeicons/core-free-icons"

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import {
  Sheet,
  SheetClose,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
} from "@/components/ui/sheet"
import { cn } from "@/lib/utils"

type AvatarStyle = {
  name: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  style: any
}

const AVATAR_STYLES: AvatarStyle[] = [
  { name: "Adventurer", style: adventurer },
  { name: "Avataaars", style: avataaars },
  { name: "Big Smile", style: bigSmile },
  { name: "Bottts", style: bottts },
  { name: "Fun Emoji", style: funEmoji },
  { name: "Lorelei", style: lorelei },
  { name: "Micah", style: micah },
  { name: "Notionists", style: notionists },
  { name: "Shapes", style: shapes },
  { name: "Thumbs", style: thumbs },
]

const SEEDS = ["Senlin", "Alice", "Bob", "Diana", "Eric", "Luna", "Max", "Zoe"]

function getInitials(name: string) {
  return name.charAt(0).toUpperCase()
}

type AvatarPickerProps = {
  value?: string
  name: string
  onChange: (avatar: string) => void
}

export function AvatarPicker({ value, name, onChange }: AvatarPickerProps) {
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [sheetOpen, setSheetOpen] = useState(false)

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (!file) return
    const reader = new FileReader()
    reader.onload = () => onChange(reader.result as string)
    reader.readAsDataURL(file)
  }

  return (
    <div className="flex items-center gap-4">
      <Avatar size="lg" className="size-20">
        {value && (
          <AvatarImage src={value} alt={name} className="object-contain" />
        )}
        <AvatarFallback className="text-2xl">
          {getInitials(name || "?")}
        </AvatarFallback>
      </Avatar>

      <input
        ref={fileInputRef}
        type="file"
        accept="image/*"
        className="hidden"
        onChange={handleFileChange}
      />

      <div className="flex flex-row gap-2">
        <Button
          type="button"
          variant="secondary"
          size="sm"
          onClick={() => setSheetOpen(true)}
        >
          Choose preset
        </Button>
        <Button
          type="button"
          variant="outline"
          size="sm"
          onClick={() => fileInputRef.current?.click()}
        >
          <HugeiconsIcon icon={Upload04Icon} strokeWidth={2} className="size-4" />
          Upload image
        </Button>
      </div>

      <PresetSheet
        open={sheetOpen}
        onOpenChange={setSheetOpen}
        value={value}
        onSelect={(v) => {
          onChange(v)
          setSheetOpen(false)
        }}
      />
    </div>
  )
}

function PresetSheet({
  open,
  onOpenChange,
  value,
  onSelect,
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  value?: string
  onSelect: (avatar: string) => void
}) {
  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent side="right" className="w-full sm:max-w-md">
        <SheetHeader>
          <SheetTitle>Choose avatar</SheetTitle>
          <SheetDescription>
            Pick from preset avatars generated by DiceBear.
          </SheetDescription>
        </SheetHeader>

        <div className="flex flex-col gap-6 overflow-y-auto px-6 pb-6">
          {AVATAR_STYLES.map((entry) => (
            <div key={entry.name} className="flex flex-col gap-2">
              <span className="text-muted-foreground text-xs font-medium">
                {entry.name}
              </span>
              <div className="grid grid-cols-4 gap-2">
                {SEEDS.map((seed) => {
                  const dataUri = createAvatar(entry.style, {
                    seed,
                    size: 80,
                  }).toDataUri()
                  const selected = value === dataUri
                  return (
                    <button
                      key={`${entry.name}-${seed}`}
                      type="button"
                      onClick={() => onSelect(dataUri)}
                      className={cn(
                        "flex items-center justify-center rounded-lg border-2 p-1 transition-all hover:bg-muted/50",
                        selected
                          ? "border-primary bg-primary/5"
                          : "border-transparent"
                      )}
                      aria-label={`Select ${entry.name} ${seed} avatar`}
                    >
                      <img
                        src={dataUri}
                        alt={`${entry.name} ${seed}`}
                        className="size-12 rounded-md"
                      />
                    </button>
                  )
                })}
              </div>
            </div>
          ))}
        </div>

        <div className="border-t p-6">
          <SheetClose asChild>
            <Button className="w-full">Done</Button>
          </SheetClose>
        </div>
      </SheetContent>
    </Sheet>
  )
}
